version: 2
orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  ios-build:
    macos:
      xcode: '13.2.1'
    working_directory: /Users/mac/Projects/React-Native/CicdIos
    shell: /bin/bash --login -o pipefail
    steps:
      # - run: gem install fastlane
      # - run: touch Gemfile
      - run: cd ios && bundle install
      # - run: gem update bundler
      # - run: bundle update
      - run: 
          command: |
            cd ios
            fastlane --version
            bundle exec fastlane release_ipa
      # - run:
      #     name: Set up iOS directory
      #     command: mkdir -p ios && cd ios && bundle exec fastlane release_ipa
      # - run: 
      #     command: |
      #       cd ios 
      #       bundle exec fastlane release_ipa
      #     no_output_timeout: 30m
workflows:
  version: 2
  build:
    jobs:
      - ios-build
# 