version: 2
orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  ios-build:
    macos:
      xcode: '13.2.1'
    working_directory: ~/repo
    shell: /bin/bash --login -o pipefail
    steps:
      - run:
          name: "Create .env file"
          command: echo -e "APP_STORE_CONNECT_API_KEY_ISSUER_ID=69a6de8a-3bf4-47e3-e053-5b8c7c11a4d1\nAPP_STORE_CONNECT_API_KEY_KEY=${APP_STORE_CONNECT_API_KEY_KEY}\nAPP_STORE_CONNECT_API_KEY_KEY_ID=4RXGZ33CNK" > .env
      - run: fastlane run bundle_install
      - run:
          command: bundle exec fastlane release_ipa --verbose
          no_output_timeout: 30m
          working_directory: ios
  ios-release:
    macos:
      xcode: '13.3.0'
    working_directory: ~/repo
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: "Create .env file"
          command: echo -e "APP_STORE_CONNECT_API_KEY_ISSUER_ID=69a6de8a-3bf4-47e3-e053-5b8c7c11a4d1\nAPP_STORE_CONNECT_API_KEY_KEY=${APP_STORE_CONNECT_API_KEY_KEY}\nAPP_STORE_CONNECT_API_KEY_KEY_ID=4RXGZ33CNK" > .env
      - run:
          command: bundle exec fastlane release_ipa --verbose
          no_output_timeout: 30m
          working_directory: ios
      - store_artifacts:
          path: ios/CicdIos.ipa
# 
workflows:
  version: 2
  build:
    jobs:
      - ios-build
      - ios-release