version: 2
orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  ios-build:
    macos:
      xcode: '13.2.1'
    working_directory: ~/repo
    shell: /bin/bash --login -o pipefail
    steps:
      - run: gem install fastlane
      - run: fastlane --version
      - run: touch Gemfile
      - run: bundle install
      - run: gem update bundler
      - run: bundle update
      - run: 
          command: bundle exec fastlane release_ipa
          no_output_timeout: 30m
          working_directory: ios
workflows:
  version: 2
  build:
    jobs:
      - ios-build
# 