version: 2
orbs:
# Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
  node:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install

      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  ios-beta:
    macos:
      xcode: '13.2.1'
    working_directory: ~/repo
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout

      - run:
          name: set Ruby version
          command: echo "ruby-2.4" > ~/.ruby-version
# ERROR
      # - restore_cache:
      #     key: npm-v1-{{ checksum "package.lock.json" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install
# ERROR
      # - save_cache:
      #     key: npm-v1-{{ checksum "package.lock.json" }}-{{ arch }}
      #     paths:
      #       - ~/.cache/npm

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
# 
      # - restore_cache:
      #     key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
      # - run: gem list fastlane
      # - run: gem install fastlane
      # # - run: gem update
      # - run: gem update fastlane
      # - run: gem update bundler
      - run:
          command: bundle install
      - run: sudo gem install fastlane -NV
          # working_directory: ios
      # - run: bundle install danger
      # - run: bundle exec danger
      # - run: cd ios && bundle exec fastlane test
      # - run: cd ios && bundle exec fastlane build

      # - run: ruby -v
      # - run: gem uninstall fastlane
      # - run: gem install fastlane
      
# ERROR
      # - save_cache:
      #     key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
      #     paths:
      #       - vendor/bundle

# ERROR IN bundle exec fastlane beta
      - run: fastlane run bundle_install
      - run:
          command: bundle exec fastlane
          working_directory: ios
          # no_output_timeout: 30m

      - store_test_results:
          path: ios/test-results

      - store_artifacts:
          path: ios/ProcureNetworks.ipa

workflows:
  version: 2
  build-deploy:
    jobs:
      - node
      - ios-beta:
          requires:
            - node