version: 2
orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  ios-build:
    macos:
      xcode: '13.2.1'
    working_directory: ~/repo
    shell: /bin/bash --login -o pipefail
    steps:
      - run: ruby --version
#  trigger that specific lane and perform the associated actions within it
      - run: fastlane run bundle_install
      - run: gem uninstall bundler
      - run: 
          working_directory: ~/repo
          command: gem install bundler
      - run: gem install fastlane
      - run: gem update bundler
      - run: gem update fastlane
      - run: touch Gemfile
      # - run: 
      #     command: xcodebuild -xcworkspace CicdIos.xcworkspace -scheme CicdIos -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/mac/Library/Developer/Xcode/Archives/2023-07-26/CicdIos\ 2023-07-26\ 14.45.18.xcarchive BUNDLE_IDENTIFIER=com.zluck.rn.demo DEVELOPMENT_TEAM=97ZG7PH35K archive
      #     working_directory: ios
      # - run: 
      #     command: cd ios && bundle exec fastlane release_ipa
      #     no_output_timeout: 30m
      - run:
          name: Set up iOS directory
          command: mkdir -p ios
      - run: bundle install
      - run: bundle update
      - run: which fastlane
      - run: bundle exec which fastlane
      # - run: bundle exec fastlane _3.0.0_ doctor
      # - run:
      #     name: Debug Info
      #     command: |
      #       echo "Current Directory: $(pwd)"
      #       echo "Ruby Version: $(ruby -v)"
      #       echo "Gem Environment: $(gem env)"
      #       which fastlane
      #       bundle exec fastlane --version
# create and release an IPA (iOS App Store Package) file
      # - run: brew install --cask
      # - run: brew cask install fastlane
      # - run: gem unistall fastlane  - ERROR
      # - run: sudo gem install fastlane -NV -n /usr/local/bin
      # - run: gem update --system
      # - run: gem install -n /usr/local/bin/ bundler
      # - run: gem install -n /usr/local/bin/ fastlane
      - run: bundle install --binstubs
      - run:
          name: Change to iOS directory and run Fastlane
          command: bundle exec fastlane release_ipa
          # bundle exec fastlane release_ipa
          no_output_timeout: 30m
  # ios-release:
  #   macos:
  #     xcode: '13.3.0'
  #   working_directory: ~/repo
  #   shell: /bin/bash --login -o pipefail
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Create .env file"
  #         command: echo -e "APP_STORE_CONNECT_API_KEY_ISSUER_ID=69a6de8a-3bf4-47e3-e053-5b8c7c11a4d1\nAPP_STORE_CONNECT_API_KEY_KEY=${APP_STORE_CONNECT_API_KEY_KEY}\nAPP_STORE_CONNECT_API_KEY_KEY_ID=4RXGZ33CNK" > .env
  #     - run: fastlane run bundle_install
  #     - run: gem install fastlane
  #     - run:
  #         command: bundle exec fastlane release_ipa
  #         no_output_timeout: 30m
  #         working_directory: ios
  #     - store_artifacts:
  #         path: ios/CicdIos.ipa
# 
workflows:
  version: 2
  build:
    jobs:
      - ios-build