# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
APP_ID = "com.zluck.rn.demo"
PROVISIONING_PROFILE_APPSTORE = "match Development com.zluck.rn.demo"
TEAM_ID = "97ZG7PH35K"

settings_to_override_release = { 
  :BUNDLE_IDENTIFIER => "com.zluck.rn.demo", 
  # :PROVISIONING_PROFILE_SPECIFIER => "com.zluck.rn.demo", 
  :DEVELOPMENT_TEAM => "97ZG7PH35K", 
}

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Export Release IPA & upload Release to App Store"
  lane :beta do
    api_key = app_store_connect_api_key( 
      key_id: "2YN89ZLRHV", 
      issuer_id: "69a6de8a-3bf4-47e3-e053-5b8c7c11a4d1", 
      key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1mLxyrIrvz/QH06R
      i1adMqsPUl8VAwVN8z2DMNepH4KgCgYIKoZIzj0DAQehRANCAATIzJKgnEbSDsly
      bHUFzQNeW1rr8EK0rn721Pb+pDtAyQaEySs8pw83ZcLLI85AWKEeZpBehWR+GRMw
      vu8F+QlL\n-----END PRIVATE KEY-----", 
    )
    increment_build_number(
      build_number: app_store_build_number(
        api_key: api_key,
        initial_build_number: "1.0",
        version: "3.0",
        live: false
      )
    )
    match(
      app_identifier: "com.zluck.rn.demo",
      readonly: is_ci,
      type: "appstore"
    )
    build_app(
      scheme: "CicdIos", 
      export_method: "app-store",
      skip_profile_detection: true,
      configuration: "Release",
      workspace: "CicdIos.xcworkspace",
      xcargs: settings_to_override_release,
      export_options: {
        provisioningProfiles: { 
          APP_ID => "com.zluck.rn.demo"
        },
        installerSigningCertificate: "/Users/mac/Downloads/CICDNEW.mobileprovision"
      }
    )
    # deliver(
    #   api_key: {
    #     key_id: "2YN89ZLRHV",
    #     issuer_id: "69a6de8a-3bf4-47e3-e053-5b8c7c11a4d1",
    #     key_filepath: "AuthKey_2YN89ZLRHV.p8"
    #   },
    #   # If we set submit_for_review: true, the new release will be sent to review automatically, so we don’t need to click on it manually from Apple Store Connect website.
    #   submit_for_review: false,
    #   # force: true,
    #   precheck_include_in_app_purchases: false
    # )
  end
end

# default_platform(:ios)

# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     increment_build_number(xcodeproj: "CicdIos.xcodeproj")
#     build_app(workspace: "CicdIos.xcworkspace", scheme: "CicdIos")
#     upload_to_testflight
#   end
# end
